Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice0', 'Random device number 0')<br>Duplicate entry 'RandomMobileDevice0' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice1', 'Random device number 1')<br>Duplicate entry 'RandomMobileDevice1' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice2', 'Random device number 2')<br>Duplicate entry 'RandomMobileDevice2' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice3', 'Random device number 3')<br>Duplicate entry 'RandomMobileDevice3' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice4', 'Random device number 4')<br>Duplicate entry 'RandomMobileDevice4' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice5', 'Random device number 5')<br>Duplicate entry 'RandomMobileDevice5' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice6', 'Random device number 6')<br>Duplicate entry 'RandomMobileDevice6' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice7', 'Random device number 7')<br>Duplicate entry 'RandomMobileDevice7' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice8', 'Random device number 8')<br>Duplicate entry 'RandomMobileDevice8' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice9', 'Random device number 9')<br>Duplicate entry 'RandomMobileDevice9' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice10', 'Random device number 10')<br>Duplicate entry 'RandomMobileDevice10' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice11', 'Random device number 11')<br>Duplicate entry 'RandomMobileDevice11' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice12', 'Random device number 12')<br>Duplicate entry 'RandomMobileDevice12' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice13', 'Random device number 13')<br>Duplicate entry 'RandomMobileDevice13' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice14', 'Random device number 14')<br>Duplicate entry 'RandomMobileDevice14' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice15', 'Random device number 15')<br>Duplicate entry 'RandomMobileDevice15' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice16', 'Random device number 16')<br>Duplicate entry 'RandomMobileDevice16' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice17', 'Random device number 17')<br>Duplicate entry 'RandomMobileDevice17' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice18', 'Random device number 18')<br>Duplicate entry 'RandomMobileDevice18' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice19', 'Random device number 19')<br>Duplicate entry 'RandomMobileDevice19' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice20', 'Random device number 20')<br>Duplicate entry 'RandomMobileDevice20' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice21', 'Random device number 21')<br>Duplicate entry 'RandomMobileDevice21' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice22', 'Random device number 22')<br>Duplicate entry 'RandomMobileDevice22' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice23', 'Random device number 23')<br>Duplicate entry 'RandomMobileDevice23' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice24', 'Random device number 24')<br>Duplicate entry 'RandomMobileDevice24' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomMobileDevice25', 'Random device number 25')<br>Duplicate entry 'RandomMobileDevice25' for key 'PRIMARY'