Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice0', 'Random device number 0')<br>Duplicate entry 'RandomDevice0' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice1', 'Random device number 1')<br>Duplicate entry 'RandomDevice1' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice2', 'Random device number 2')<br>Duplicate entry 'RandomDevice2' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice3', 'Random device number 3')<br>Duplicate entry 'RandomDevice3' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice4', 'Random device number 4')<br>Duplicate entry 'RandomDevice4' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice5', 'Random device number 5')<br>Duplicate entry 'RandomDevice5' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice6', 'Random device number 6')<br>Duplicate entry 'RandomDevice6' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice7', 'Random device number 7')<br>Duplicate entry 'RandomDevice7' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice8', 'Random device number 8')<br>Duplicate entry 'RandomDevice8' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice9', 'Random device number 9')<br>Duplicate entry 'RandomDevice9' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice10', 'Random device number 10')<br>Duplicate entry 'RandomDevice10' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice11', 'Random device number 11')<br>Duplicate entry 'RandomDevice11' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice12', 'Random device number 12')<br>Duplicate entry 'RandomDevice12' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice13', 'Random device number 13')<br>Duplicate entry 'RandomDevice13' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice14', 'Random device number 14')<br>Duplicate entry 'RandomDevice14' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice15', 'Random device number 15')<br>Duplicate entry 'RandomDevice15' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice16', 'Random device number 16')<br>Duplicate entry 'RandomDevice16' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice17', 'Random device number 17')<br>Duplicate entry 'RandomDevice17' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice18', 'Random device number 18')<br>Duplicate entry 'RandomDevice18' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice19', 'Random device number 19')<br>Duplicate entry 'RandomDevice19' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice20', 'Random device number 20')<br>Duplicate entry 'RandomDevice20' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice21', 'Random device number 21')<br>Duplicate entry 'RandomDevice21' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice22', 'Random device number 22')<br>Duplicate entry 'RandomDevice22' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice23', 'Random device number 23')<br>Duplicate entry 'RandomDevice23' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice24', 'Random device number 24')<br>Duplicate entry 'RandomDevice24' for key 'PRIMARY'Error: INSERT INTO device (deviceId, description)
	VALUES ('RandomDevice25', 'Random device number 25')<br>Duplicate entry 'RandomDevice25' for key 'PRIMARY'